### ISSUE TITLE
Move sseType to configuration

### ISSUE THREAD

**Issue by yellow-sky** [C2FO/vfs#98]
There is currently no way to change the sse type or disable it.

**Comment by funkyshu** [comment]
Agreed that this should be optional.  We are planning out a v6 release which includes revamping our options work.  There will be global options as well as certain per-request options like:
```go
localFile.CopyTo(remoteS3File, WithUseSEE())
```
The form of most options will be [variadic functional options](https://dave.cheney.net/2014/10/17/functional-options-for-friendly-apis).

**Comment by naucon** [comment]
Hi @funkyshu,

I'm also having trouble connecting to a Ceph Object Gateway via the S3 backend due to mandatory server-side encryption. There is a pull request (https://github.com/C2FO/vfs/pull/114) that makes the option configurable.
It would be great if you could merge the PR into v6 and we don't have to wait for v7.

If you have problems with the pull request, I can create a new PR that suits your needs. Please let me know.
